<?php
/**
 * Drug
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vericred\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * Drug Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Vericred\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Drug implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    static $swaggerModelName = 'Drug';

    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'ndc' => 'string',
        'proprietary_name' => 'string',
        'non_proprietary_name' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'ndc' => 'ndc',
        'proprietary_name' => 'proprietary_name',
        'non_proprietary_name' => 'non_proprietary_name'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'ndc' => 'setNdc',
        'proprietary_name' => 'setProprietaryName',
        'non_proprietary_name' => 'setNonProprietaryName'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'ndc' => 'getNdc',
        'proprietary_name' => 'getProprietaryName',
        'non_proprietary_name' => 'getNonProprietaryName'
    );
  
    static function getters() {
        return self::$getters;
    }

    /**
      * $ndc National Drug Code ID
      * @var string
      */
    protected $ndc;
    /**
      * $proprietary_name Proprietary name of drug
      * @var string
      */
    protected $proprietary_name;
    /**
      * $non_proprietary_name Non-proprietary name of drug
      * @var string
      */
    protected $non_proprietary_name;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        
        if ($data != null) {
            $this->ndc = $data["ndc"];
            $this->proprietary_name = $data["proprietary_name"];
            $this->non_proprietary_name = $data["non_proprietary_name"];
        }
    }
    /**
     * Gets ndc
     * @return string
     */
    public function getNdc()
    {
        return $this->ndc;
    }
  
    /**
     * Sets ndc
     * @param string $ndc National Drug Code ID
     * @return $this
     */
    public function setNdc($ndc)
    {
        
        $this->ndc = $ndc;
        return $this;
    }
    /**
     * Gets proprietary_name
     * @return string
     */
    public function getProprietaryName()
    {
        return $this->proprietary_name;
    }
  
    /**
     * Sets proprietary_name
     * @param string $proprietary_name Proprietary name of drug
     * @return $this
     */
    public function setProprietaryName($proprietary_name)
    {
        
        $this->proprietary_name = $proprietary_name;
        return $this;
    }
    /**
     * Gets non_proprietary_name
     * @return string
     */
    public function getNonProprietaryName()
    {
        return $this->non_proprietary_name;
    }
  
    /**
     * Sets non_proprietary_name
     * @param string $non_proprietary_name Non-proprietary name of drug
     * @return $this
     */
    public function setNonProprietaryName($non_proprietary_name)
    {
        
        $this->non_proprietary_name = $non_proprietary_name;
        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Vericred\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Vericred\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}
