<?php
/**
 * Query
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vericred\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * Query Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Vericred\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Query implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    static $swaggerModelName = 'query';

    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'applicants' => '\Swagger\Client\Model\Applicant[]',
        'enrollment_date' => '\DateTime',
        'fips_code' => 'string',
        'household_income' => 'string',
        'household_size' => 'string',
        'market' => 'string',
        'providers' => 'string[]',
        'zip_code' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'applicants' => 'applicants',
        'enrollment_date' => 'enrollment_date',
        'fips_code' => 'fips_code',
        'household_income' => 'household_income',
        'household_size' => 'household_size',
        'market' => 'market',
        'providers' => 'providers',
        'zip_code' => 'zip_code'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'applicants' => 'setApplicants',
        'enrollment_date' => 'setEnrollmentDate',
        'fips_code' => 'setFipsCode',
        'household_income' => 'setHouseholdIncome',
        'household_size' => 'setHouseholdSize',
        'market' => 'setMarket',
        'providers' => 'setProviders',
        'zip_code' => 'setZipCode'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'applicants' => 'getApplicants',
        'enrollment_date' => 'getEnrollmentDate',
        'fips_code' => 'getFipsCode',
        'household_income' => 'getHouseholdIncome',
        'household_size' => 'getHouseholdSize',
        'market' => 'getMarket',
        'providers' => 'getProviders',
        'zip_code' => 'getZipCode'
    );
  
    static function getters() {
        return self::$getters;
    }

    /**
      * $applicants 
      * @var \Swagger\Client\Model\Applicant[]
      */
    protected $applicants;
    /**
      * $enrollment_date 
      * @var \DateTime
      */
    protected $enrollment_date;
    /**
      * $fips_code 
      * @var string
      */
    protected $fips_code;
    /**
      * $household_income 
      * @var string
      */
    protected $household_income;
    /**
      * $household_size 
      * @var string
      */
    protected $household_size;
    /**
      * $market 
      * @var string
      */
    protected $market;
    /**
      * $providers 
      * @var string[]
      */
    protected $providers;
    /**
      * $zip_code 
      * @var string
      */
    protected $zip_code;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        
        if ($data != null) {
            $this->applicants = $data["applicants"];
            $this->enrollment_date = $data["enrollment_date"];
            $this->fips_code = $data["fips_code"];
            $this->household_income = $data["household_income"];
            $this->household_size = $data["household_size"];
            $this->market = $data["market"];
            $this->providers = $data["providers"];
            $this->zip_code = $data["zip_code"];
        }
    }
    /**
     * Gets applicants
     * @return \Swagger\Client\Model\Applicant[]
     */
    public function getApplicants()
    {
        return $this->applicants;
    }
  
    /**
     * Sets applicants
     * @param \Swagger\Client\Model\Applicant[] $applicants 
     * @return $this
     */
    public function setApplicants($applicants)
    {
        
        $this->applicants = $applicants;
        return $this;
    }
    /**
     * Gets enrollment_date
     * @return \DateTime
     */
    public function getEnrollmentDate()
    {
        return $this->enrollment_date;
    }
  
    /**
     * Sets enrollment_date
     * @param \DateTime $enrollment_date 
     * @return $this
     */
    public function setEnrollmentDate($enrollment_date)
    {
        
        $this->enrollment_date = $enrollment_date;
        return $this;
    }
    /**
     * Gets fips_code
     * @return string
     */
    public function getFipsCode()
    {
        return $this->fips_code;
    }
  
    /**
     * Sets fips_code
     * @param string $fips_code 
     * @return $this
     */
    public function setFipsCode($fips_code)
    {
        
        $this->fips_code = $fips_code;
        return $this;
    }
    /**
     * Gets household_income
     * @return string
     */
    public function getHouseholdIncome()
    {
        return $this->household_income;
    }
  
    /**
     * Sets household_income
     * @param string $household_income 
     * @return $this
     */
    public function setHouseholdIncome($household_income)
    {
        
        $this->household_income = $household_income;
        return $this;
    }
    /**
     * Gets household_size
     * @return string
     */
    public function getHouseholdSize()
    {
        return $this->household_size;
    }
  
    /**
     * Sets household_size
     * @param string $household_size 
     * @return $this
     */
    public function setHouseholdSize($household_size)
    {
        
        $this->household_size = $household_size;
        return $this;
    }
    /**
     * Gets market
     * @return string
     */
    public function getMarket()
    {
        return $this->market;
    }
  
    /**
     * Sets market
     * @param string $market 
     * @return $this
     */
    public function setMarket($market)
    {
        
        $this->market = $market;
        return $this;
    }
    /**
     * Gets providers
     * @return string[]
     */
    public function getProviders()
    {
        return $this->providers;
    }
  
    /**
     * Sets providers
     * @param string[] $providers 
     * @return $this
     */
    public function setProviders($providers)
    {
        
        $this->providers = $providers;
        return $this;
    }
    /**
     * Gets zip_code
     * @return string
     */
    public function getZipCode()
    {
        return $this->zip_code;
    }
  
    /**
     * Sets zip_code
     * @param string $zip_code 
     * @return $this
     */
    public function setZipCode($zip_code)
    {
        
        $this->zip_code = $zip_code;
        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Vericred\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Vericred\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}
