<?php
/**
 * PlanSearchResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vericred\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * PlanSearchResponse Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Vericred\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlanSearchResponse implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    static $swaggerModelName = 'PlanSearchResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'meta' => '\Swagger\Client\Model\Meta',
        'plans' => '\Swagger\Client\Model\Plan[]',
        'coverages' => '\Swagger\Client\Model\Drug[]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'meta' => 'meta',
        'plans' => 'plans',
        'coverages' => 'coverages'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'meta' => 'setMeta',
        'plans' => 'setPlans',
        'coverages' => 'setCoverages'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'meta' => 'getMeta',
        'plans' => 'getPlans',
        'coverages' => 'getCoverages'
    );
  
    static function getters() {
        return self::$getters;
    }

    /**
      * $meta Metadata for query
      * @var \Swagger\Client\Model\Meta
      */
    protected $meta;
    /**
      * $plans Plan search results
      * @var \Swagger\Client\Model\Plan[]
      */
    protected $plans;
    /**
      * $coverages null
      * @var \Swagger\Client\Model\Drug[]
      */
    protected $coverages;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        
        if ($data != null) {
            $this->meta = $data["meta"];
            $this->plans = $data["plans"];
            $this->coverages = $data["coverages"];
        }
    }
    /**
     * Gets meta
     * @return \Swagger\Client\Model\Meta
     */
    public function getMeta()
    {
        return $this->meta;
    }
  
    /**
     * Sets meta
     * @param \Swagger\Client\Model\Meta $meta Metadata for query
     * @return $this
     */
    public function setMeta($meta)
    {
        
        $this->meta = $meta;
        return $this;
    }
    /**
     * Gets plans
     * @return \Swagger\Client\Model\Plan[]
     */
    public function getPlans()
    {
        return $this->plans;
    }
  
    /**
     * Sets plans
     * @param \Swagger\Client\Model\Plan[] $plans Plan search results
     * @return $this
     */
    public function setPlans($plans)
    {
        
        $this->plans = $plans;
        return $this;
    }
    /**
     * Gets coverages
     * @return \Swagger\Client\Model\Drug[]
     */
    public function getCoverages()
    {
        return $this->coverages;
    }
  
    /**
     * Sets coverages
     * @param \Swagger\Client\Model\Drug[] $coverages null
     * @return $this
     */
    public function setCoverages($coverages)
    {
        
        $this->coverages = $coverages;
        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Vericred\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Vericred\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}
